
@startuml
' Packages
package JavaLogik {
  class Benutzer {
    - int id
    - String name
    - String email
    - String password
    - String rolle
    - Kalender kalender
    --
    + Benutzer(String name, String email, String password, String rolle)
    + int getId()
    + String getName()
    + String getEmail()
    + String getPassword()
    + String getRolle()
    + Kalender getKalender()
    + void setName(String name)
    + void setEmail(String email)
    + void setPassword(String password)
    + void setRolle(String rolle)
  }

  class Familie {
    - String familienName
    - java.util.List<Benutzer> mitglieder
    --
    + Familie(String familienName)
    + {static} Familie erstelleFamilie(String familienName)
    + String getFamilienName()
    + List<Benutzer> getMitglieder()
    + boolean benutzernameExistiert(String name)
    + boolean erstelleBenutzer(String name, String email, String password, String rolle)
    + void benutzerHinzufuegen(Benutzer benutzer)
    + void benutzerLoeschen(Benutzer benutzer)
    + void setFamilienName(String familienName)
    + boolean benutzerBearbeiten(Benutzer benutzer, String neuerName, String neueEmail, String neuesPasswort, String neueRolle)
    + List<String> getBenutzerNamen()
  }

  class Kalender {
    - int id
    - List<Termin> termine
    - List<Kategorie> kategorien
    --
    + Kalender()
    + int getId()
    + List<Termin> getTermine()
    + List<Kategorie> getKategorien()
    + List<String> getKategorienNamen()
    + void terminErstellenUndHinzufuegen(Termin termin)
    + void terminLoeschen(Termin termin)
    + void removeKategorie(Kategorie kategorie)
    + boolean konflikt(Termin neuerTermin)
    + void kategorieHinzufuegen(Kategorie kategorie)
    + boolean kategorienEnthalten(Kategorie kategorie)
    + List<Termin> termineSuchen(String name)
    + boolean terminErstellenUndHinzufuegen(String titel, java.time.Instant start, java.time.Instant ende, String beschreibung, Kategorie kategorie)
    + boolean kategorieDoppelt(String name)
    + boolean erstelleKategorie(String name, String farbe)
    + boolean terminBearbeiten(Termin termin, String neuerTitel, java.time.Instant neuerStart, java.time.Instant neuesEnde, String neueBeschreibung, Kategorie neueKategorie)
    + List<Termin> getTermineForDate(java.time.LocalDate date)
    + Kategorie getKategorieByName(String name)
  }

  class Kategorie {
    - int id
    - String name
    - String farbe
    --
    + Kategorie(String name, String farbe)
    + int getId()
    + String getName()
    + String getFarbe()
    + void setName(String name)
    + void setFarbe(String farbe)
  }

  class Termin {
    - int id
    - String titel
    - java.time.Instant start
    - java.time.Instant ende
    - String beschreibung
    - Kategorie kategorie
    --
    + Termin(String titel, java.time.Instant start, java.time.Instant ende, String beschreibung, Kategorie kategorie)
    + int getId()
    + String getTitel()
    + java.time.Instant getStart()
    + java.time.Instant getEnde()
    + String getBeschreibung()
    + Kategorie getKategorie()
    + void setTitel(String titel)
    + void setDatum(java.time.Instant start)
    + void setEnde(java.time.Instant ende)
    + void setBeschreibung(String beschreibung)
    + void setKategorie(Kategorie kategorie)
  }

  class MainLogik {
    - String currentUserName
    --
    + main()
    + demosErstellen()
    + void setCurrentUserName(String name)
    + String getCurrentUserName()
    + List<Termin> getTermineForDate(java.time.LocalDate date)
    + List<String> getBenutzerNamen()
    + List<String> getKategorienNamen()
    + Kategorie getKategorieByName(String name)
    + void addTermin(Termin t)
  }
}

package GUI {
  class DayView {
    - header
    - infoLabel
    - VBox linkeSpalte
    - VBox stundenMarkierung
    - Pane eventLayer
    - LocalDate aktuellesDatum
    --
    + DayView()
    + void show(LocalDate date, List<Termin> termine)
  }

  class BenutzerAdd {
    -extends Stage
    -TextField emailField
    -PasswordField passwordField
    -TextField rolleField
    --
    + onSave()
}
  class StandardAnsicht {
    - boolean isDayView
    - VBox monthViewHolder
    - DayView dayView
    - Stage standartLayout
    - LocalDate akutellAngezeigtesDatum
    - Label aktuellerBenutzer
    - Label aktuellerMonat
    - Label aktuelleZeit
    - GridPane kalenderGrid
    - Button ansichtWechsel
    --
    + void start()
    + void renderCalendar()
    + void showMonthView()
    + void showDayView(LocalDate date)
    + void applyHover(Button b)
  }

  class TerminAdd {
    -TextField titelEingabe
    -DatePicker startDatum
    -TextField startZeit
    -DataPicker endDatum
    -TextField endZeit
    -TextArea beschreibung
    -ComboBox<String> kategorienAuswahl
    --
    + TerminAdd()
    + TerminBearbeiten()
    + OnSave()
  }

  class KategorieAdd {
  -extends stage
  -TextField nameField
  -ColorPicker colorPicker
  --
  +onSave()
  }
}

' Relationships / Associations
JavaLogik.Benutzer "1" o-- "1" JavaLogik.Kalender : besitzt
JavaLogik.Familie "1" o-- "1..*" JavaLogik.Benutzer : mitglieder
JavaLogik.Familie   <--   JavaLogik.MainLogik
JavaLogik.Kalender "1" o-- "0..*" JavaLogik.Termin : termine
JavaLogik.Kalender "1..*" o-- "0..*" JavaLogik.Kategorie : kategorien
JavaLogik.Termin "0..*" --> "0..1" JavaLogik.Kategorie
GUI.StandardAnsicht <-- GUI.DayView
GUI.StandardAnsicht --> JavaLogik.MainLogik
GUI.TerminAdd --> JavaLogik.MainLogik
GUI.TerminAdd --> GUI.StandardAnsicht
GUI.BenutzerAdd --> GUI.StandardAnsicht
GUI.KategorieAdd --> GUI.TerminAdd
@enduml